[package]
name = "rusty_markets"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
futures-util = "0.3.31"
rand = "0.9.1"
rust_decimal = { version = "1.37.1"}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
url = "2.5.1"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
# native-tls is probably audited better than rustls, so we choose that,
# even though rustls likely has fewer bugs due to more rust and less legacy.
tokio-tungstenite = {version = "0.26.2", features = ["url", "native-tls"]}
