pub struct SymbolPair(String);

impl SymbolPair {
    /// Yields None if the string does not represent a valid currency pair.
    pub fn new(s: String) -> Result<SymbolPair, String> {
        if is_currency_pair(s.as_str()) {
            Ok(SymbolPair(s))
        } else {
            Err(format!("{s} is not a valid currency pair"))
        }
    }
    pub fn get(&self) -> &str {
        self.0.as_str()
    }
}

impl std::fmt::Display for SymbolPair {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.get().fmt(f)
    }
}

// Whether the string represents a valid Bitstamp currency pair.
fn is_currency_pair(s: &str) -> bool {
    BITSTAMP_CURRENCY_PAIRS.binary_search(&s).is_ok()
}

// Currency pairs accepted by the bitstamp exchange, sorted alphabetically.
// Source: https://www.bitstamp.net/websocket/v2/
// TODO: Find such a list for individual currencies, and for binance.
const BITSTAMP_CURRENCY_PAIRS: [&str; 245] = [
    "1incheur",
    "1inchusd",
    "aavebtc",
    "aaveeur",
    "aaveusd",
    "adabtc",
    "adaeur",
    "adausd",
    "algoeur",
    "algousd",
    "ampeur",
    "ampusd",
    "apeeur",
    "apeusd",
    "arbeur",
    "arbusd",
    "audioeur",
    "audiousd",
    "avaxeur",
    "avaxusd",
    "axseur",
    "axsusd",
    "bandeur",
    "bandusd",
    "bateur",
    "batusd",
    "bchbtc",
    "bcheur",
    "bchusd",
    "blureur",
    "blurusd",
    "bomeeur",
    "bomeusd",
    "bonkeur",
    "bonkusd",
    "btceur",
    "btcgbp",
    "btcrlusd",
    "btcusd",
    "btcusdc",
    "btcusdt",
    "chzeur",
    "chzusd",
    "compeur",
    "compusd",
    "coreumeur",
    "coreumusd",
    "crveur",
    "crvusd",
    "cspreur",
    "csprusd",
    "ctsieur",
    "ctsiusd",
    "ctxeur",
    "ctxusd",
    "cxteur",
    "cxtusd",
    "daiusd",
    "dgldeur",
    "dgldusd",
    "dogeeur",
    "dogeusd",
    "doteur",
    "dotusd",
    "dydxeur",
    "dydxusd",
    "egldeur",
    "egldusd",
    "enjeur",
    "enjusd",
    "enseur",
    "ensusd",
    "eth2eth",
    "ethbtc",
    "etheur",
    "ethgbp",
    "ethrlusd",
    "ethusd",
    "ethusdc",
    "ethusdt",
    "eurcveur",
    "eurcvusdt",
    "euroceur",
    "eurocusdc",
    "eurusd",
    "feteur",
    "fetusd",
    "flokieur",
    "flokiusd",
    "flreur",
    "flrusd",
    "ftmeur",
    "ftmusd",
    "galaeur",
    "galausd",
    "gbpusd",
    "grteur",
    "grtusd",
    "gyenusd",
    "hbareur",
    "hbarusd",
    "icpeur",
    "icpusd",
    "imxeur",
    "imxusd",
    "injeur",
    "injusd",
    "jupeur",
    "jupusd",
    "knceur",
    "kncusd",
    "ldoeur",
    "ldousd",
    "linkbtc",
    "linkeur",
    "linkgbp",
    "linkusd",
    "lmwreur",
    "lmwrusd",
    "lrceur",
    "lrcusd",
    "ltcbtc",
    "ltceur",
    "ltcusd",
    "manaeur",
    "manausd",
    "maticeur",
    "maticusd",
    "melaniaeur",
    "melaniausd",
    "meweur",
    "mewusd",
    "mkreur",
    "mkrusd",
    "mogeur",
    "mogusd",
    "neareur",
    "nearusd",
    "nexoeur",
    "nexousd",
    "ondoeur",
    "ondousd",
    "opeur",
    "opusd",
    "pepeeur",
    "pepeusd",
    "perpeur",
    "perpusd",
    "popcateur",
    "popcatusd",
    "pytheur",
    "pythusd",
    "pyusdeur",
    "pyusdusd",
    "radeur",
    "radusd",
    "rlusdeur",
    "rlusdusd",
    "rlusdusdt",
    "rlyeur",
    "rlyusd",
    "rndreur",
    "rndrusd",
    "sandeur",
    "sandusd",
    "seieur",
    "seiusd",
    "sgbeur",
    "sgbusd",
    "shibeur",
    "shibusd",
    "skleur",
    "sklusd",
    "slpeur",
    "slpusd",
    "smteur",
    "smtusd",
    "snxeur",
    "snxusd",
    "soleur",
    "solusd",
    "storjeur",
    "storjusd",
    "strkeur",
    "strkusd",
    "suieur",
    "suiusd",
    "sushieur",
    "sushiusd",
    "syrupeur",
    "syrupusd",
    "traceur",
    "tracusd",
    "trufeur",
    "trufusd",
    "trumpeur",
    "trumpusd",
    "umaeur",
    "umausd",
    "unibtc",
    "unieur",
    "uniusd",
    "usdceur",
    "usdcusd",
    "usdcusdt",
    "usdteur",
    "usdtusd",
    "vchfeur",
    "vchfusd",
    "veureur",
    "veurusd",
    "vexteur",
    "vextusd",
    "wbtcbtc",
    "wecaneur",
    "wecanusd",
    "weneur",
    "wenusd",
    "wifeur",
    "wifusd",
    "wooeur",
    "woousd",
    "xchngeur",
    "xchngusd",
    "xdceur",
    "xdcusd",
    "xlmbtc",
    "xlmeur",
    "xlmgbp",
    "xlmusd",
    "xrpbtc",
    "xrpeur",
    "xrpgbp",
    "xrprlusd",
    "xrpusd",
    "xrpusdt",
    "xsgdusd",
    "xsgdusdt",
    "yfieur",
    "yfiusd",
    "zetaeur",
    "zetausd",
    "zrxeur",
    "zrxusd",
    "zusdusd",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_sorted() {
        assert!(BITSTAMP_CURRENCY_PAIRS.is_sorted());
    }

    #[test]
    fn validation_works() {
        assert!(BITSTAMP_CURRENCY_PAIRS.iter().all(|s| is_currency_pair(&s)));
        assert!(!is_currency_pair(""));
        assert!(!is_currency_pair("apple"));
        assert!(!is_currency_pair("banana"));
        assert!(!is_currency_pair(" "));
        assert!(!is_currency_pair("btc"));
        assert!(is_currency_pair("1incheur"));
        assert!(!is_currency_pair("1incheur "));
        assert!(!is_currency_pair(" 1incheur"));
    }
}
